# Theme settings
doks:
    baseurl: /docs
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Item 1
              item_url: '#'
            - item_name: Item 2
              item_url: '#'
            - item_name: Item 3
              item_url: '#'
    footer:
        content:
            logo:
                text: OpenAir Collective
                image:
            copyright: Copyright &copy; 2022 - OpenAir Collective <br>All rights reserved.
        social_list:
            - network_name: twitter
              profile_url: 'https://twitter.com/openaircollect'
            - network_name: youtube
              profile_url: 'https://www.youtube.com/channel/UCxG5KAao5rJY3vvwbVUSv4g'
            - network_name: instagram
              profile_url: 'https://www.instagram.com/theopenaircollective/?hl=en'
            - network_name: linkedin
              profile_url: 'https://www.linkedin.com/company/openair-collective'
            - network_name: github
              profile_url: 'https://github.com/openair-collective'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
